import Modal from './playground/Modal'
import Tabs from './playground/Tabs'
import Disclosure from './playground/Disclosure'
import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog'
import {
  Tabs as ShadcnTabs,
  TabsContent,
  TabsList,
  TabsTrigger,
} from '@/components/ui/tabs'
import './App.css'

function App() {
  return (
    <>
      <Modal />
      <Tabs />
      <Disclosure />
      <section className="shadcn-playground" aria-labelledby="shadcn-heading">
        <p className="eyebrow">Component comparison</p>
        <h2 id="shadcn-heading">shadcn/ui</h2>
        <div className="shadcn-examples">
          <Dialog>
            <DialogTrigger asChild>
              <Button>Open shadcn Dialog</Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>shadcn Dialog</DialogTitle>
                <DialogDescription>
                  This dialog is generated by shadcn/ui and built on Radix UI.
                </DialogDescription>
              </DialogHeader>
            </DialogContent>
          </Dialog>

          <ShadcnTabs defaultValue="profile" className="shadcn-tabs">
            <TabsList aria-label="shadcn account sections">
              <TabsTrigger value="profile">Profile</TabsTrigger>
              <TabsTrigger value="settings">Settings</TabsTrigger>
            </TabsList>
            <TabsContent value="profile">Profile content</TabsContent>
            <TabsContent value="settings">Settings content</TabsContent>
          </ShadcnTabs>
        </div>
      </section>
    </>
  )
}

export default App
